[project]
name = "profile-plotter"
version = "0.1.0"
description = ""
authors = ["DarkenedDragon <eridor314@gmail.com>"]
readme = "README.md"
package-mode = false
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
]

